blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/amazingandyyy/gofuzzyclone/issues/new
    about: Thank you for using! Feel free report any bug you encounter.
  - name: Feature request
    url: https://github.com/amazingandyyy/gofuzzyclone/issues/new
    about: Love to have a feature? Let me know!
  - name: Follow author
    url: https://github.com/amazingandyyy
    about: Feel free to follow me!
